name: Build and deploy
on:
  push:
    tags:
      - "v*.*.*"
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_VERSION: 16
      STRIPE_TEST_PK: ${{ secrets.STRIPE_TEST_PK }}
      STRIPE_TEST_SK: ${{ secrets.STRIPE_TEST_SK }}
    steps:
      - name: Сheckout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Run builder
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Archiving lib directory
        uses: actions/upload-artifact@v3
        with:
          name: lib
          path: ${{ github.workspace }}/lib
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    env:
      NODE_VERSION: 16
    steps:
      - name: Сheckout repo
        uses: actions/checkout@v3
      - name: Unarchiving lib directory
        uses: actions/download-artifact@v3
        with:
          name: lib
          path: ${{ github.workspace }}/lib
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install modules
        run: npm ci
      - name: Create Release
        id: create_release
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            see [CHANGELOG.md](https://github.com/siarheidudko/stripe-js/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false
      - name: Set registry npm packages
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Publish package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
